# Generated by Django 4.2.16 on 2024-11-21 03:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_alter_menu_inventory_alter_menu_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='number_of_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='no_of_guests',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(),
        ),
    ]
